Hw04 auth
ihorlihus/nodejs-homework-rest-api pull request #3
Opened 2022-11-21 00:30 UTC by ihorlihus

DB_HOST=mongodb+srv://ligusigor:P1K4FhGA0fiwSJed@cluster0.3zi2fhc.mongodb.net/contacts-db
PORT=3000
JWT_SEKRET=sekret

2022-11-21 16:16 UTC, Eastvarga commented on app.js
> +app.use("/api/auth", authRouter);
Чому раути не відповідають ДЗ?

2022-11-21 16:18 UTC, Eastvarga commented on controllers/authController.js
> +  const token = jwt.sign({ _id: user._id }, JWT_SECRET.toString(), {
навіщо JWT_SECRET.toString() якщо змінна з env процесу завжди строка?

2022-11-21 16:18 UTC, Eastvarga commented on controllers/authController.js
> +  console.log(user);
консолі не прибрали

2022-11-21 16:21 UTC, Eastvarga commented on middlewares/validateEmailPass.js
> +async function validateEmailPass(req, res, next) {
А що це таке? Це повинна буди схема валідації юзера. А не якесь пошта-пароль

2022-11-21 16:22 UTC, Eastvarga commented on models/users.model.js
> +const schemaValidMailPassJoi = Joi.object({
Навіщо це, якщо є схема юзера? Що це за дублювання непотрібне?

2022-11-21 16:24 UTC, Eastvarga commented on routes/api/auth.router.js
> +  tryCatchWrapper(validateEmailPass),
Тут повинна бути валідація юзера перед створенням

2022-11-21 16:25 UTC, Eastvarga commented on routes/api/auth.router.js
> +router.get("/logout", tryCatchWrapper(middleware), tryCatchWrapper(logout));
Ніяких загальних назв. middleware - який функціонал має? тут можно auth зрозуміти но не middleware

2022-11-21 16:26 UTC, Eastvarga commented on routes/api/contacts.router.js
>  router.get("/", tryCatchWrapper(getAll));
Де попередній мідлвар авторізації який не дає доступу до раута без токена?

2022-11-21 16:27 UTC, Eastvarga commented on routes/api/user.router.js
> +userRouter.get(
Чому тут зайві раути?

2022-11-21 16:28 UTC, Eastvarga commented on server.js
>  const { DB_HOST, PORT } = process.env;
PORT =3000 зазвичай для пору використовують дефолтне значення (для розробки)

2022-11-21 16:28 UTC, Eastvarga requested changes
Є зауваження, треба їх усунути

2022-11-24 15:24 UTC, ihorlihus commented on app.js
> +app.use("/api/auth", authRouter);
Виправивлено

2022-11-24 15:28 UTC, ihorlihus commented on controllers/authController.js
> +  const token = jwt.sign({ _id: user._id }, JWT_SECRET.toString(), {
З нею були проблеми, без приведення до строки, вона undefined. Витратив на це багато часу, підкажіть що зробити чи де почитати

2022-11-24 15:28 UTC, ihorlihus commented on controllers/authController.js
> +  console.log(user);
Виправлено

2022-11-24 15:30 UTC, ihorlihus commented on middlewares/validateEmailPass.js
> +async function validateEmailPass(req, res, next) {
Виправлено

2022-11-24 15:32 UTC, ihorlihus commented on models/users.model.js
> +const schemaValidMailPassJoi = Joi.object({
Переробив через validateSync()

2022-11-24 15:32 UTC, ihorlihus commented on routes/api/auth.router.js
> +  tryCatchWrapper(validateEmailPass),
Виправлено

2022-11-24 15:32 UTC, ihorlihus commented on routes/api/auth.router.js
> +router.get("/logout", tryCatchWrapper(middleware), tryCatchWrapper(logout));
Виправлено

2022-11-24 15:36 UTC, ihorlihus commented on routes/api/contacts.router.js
>  router.get("/", tryCatchWrapper(getAll));
Тобто я правильно розумію, що весь CRUD треба зробити юзеру? В такому випадку, залишати загальний CRUD по контактам і базу даних до них?

2022-11-24 15:37 UTC, ihorlihus commented on routes/api/user.router.js
> +userRouter.get(
Питання перетинається з попереднім

2022-11-24 15:40 UTC, ihorlihus commented on server.js
>  const { DB_HOST, PORT } = process.env;
яке дефолтне значення?

2022-11-25 14:33 UTC, Eastvarga approved these changes

2022-11-25 15:28 UTC, merged