Hw05 avatars
ihorlihus/nodejs-homework-rest-api pull request #4
Opened 2022-11-29 07:38 UTC by ihorlihus

2022-11-29 20:15 UTC, Eastvarga requested changes
Є зауваження

2022-11-29 20:15 UTC, Eastvarga commented on controllers/avatarController.js
> +    "public/avatars",
Якщо цих тек не існує, тоді ваш сервер не працює! 
Треба забезпечити існування цих тек у файловій системі

2022-11-29 20:15 UTC, Eastvarga commented on controllers/avatarController.js
> +      file,
Не вірно, відповідь не відповідає ДЗ

2022-11-29 20:15 UTC, Eastvarga commented on app.js
> +app.use("/avatars", express.static("public/avatars"));
Не вірно
app.use(express.static("public"));
ось вірний запис 
Почитайте, чому.
Але це не зауваженя, а коментар. Бо для зображень це буде працювати, але є нюанси, котрі Ви повинні розуміти коли так робите.

2022-11-29 20:41 UTC, ihorlihus commented on controllers/avatarController.js
> +      file,
Виправлено

2022-11-29 20:41 UTC, ihorlihus commented on controllers/avatarController.js
> +    "public/avatars",
Виправлено

2022-11-29 20:53 UTC, ihorlihus commented on app.js
> +app.use("/avatars", express.static("public/avatars"));
Почитав, виправив

2022-11-30 14:31 UTC, Eastvarga requested changes
Передивіться матеріал уважніше.
Трнба доопрацювати. / чи \ розумієте різницю?

2022-11-30 14:31 UTC, Eastvarga commented on controllers/avatarController.js
> -    "public/avatars",
Тут не треба було видаляти avatars

2022-11-30 14:31 UTC, Eastvarga commented on controllers/avatarController.js
> +  const avatarURL = user.avatarURL;
Не вірно, плутаєте  запис урл лінки з записом шляху файлової системи

2022-12-01 19:20 UTC, Eastvarga commented on app.js
> +app.use("/public", express.static("public"));
app.use( express.static("public"));
статичною зазвичай роблять до кореня хосту
такий запис дає можливість отримати за посиланням
http://localhost:3000/avatars/image.jpg
файл котрий знаходиться у ./public/avatars/image.jpg

2022-12-01 19:22 UTC, Eastvarga commented on controllers/avatarController.js
> +        avatarURL: "/public/avatars/" + avatarName,
`${HOST}/avatars/${avatarName}`
HOST= process.env.HOST || http://localhost:3000/ 
Вот так треба було зробити =)

2022-12-01 19:22 UTC, Eastvarga approved these changes

2022-12-01 19:23 UTC, merged